audit_header: false
title: Southern California Wealth Management Video Blog with Rene Castro
description: Our mission at Elite Wealth and Tax Planning is to be your best resource for Southern California Wealth Management advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about Wealth Management. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Elite Wealth and Tax Planning.
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Rene Castro
  title:
  license_number:
  about_markdown: |
    Rene Castro, founder of Elite Wealth and Tax Planning, is an extremely passionate teacher as well as dedicated student of Elite Wealth and Tax Planning. For the last 20+ years, he has worked collaboratively with CPAs, Enrolled Tax Agents, Certified Financial PlannerTM professionals, Estate Attorneys, Tax attorneys and other professionals to help them provide comprehensive advanced tax planning, wealth management, and business advisory pulls and systems.

    Rene loves working with his team of experts to educate, empower, and maximize the success of his strategic partners, thus allowing them to enjoy greater freedom in their personal and professional lives.
  brand: Elite Wealth and Tax Planning
  brokerage:
  market: Southern California
  address: 1425 W. Foothill Blvd. Suite 123 Upland, CA 91786
  phone: 909-635-8926
  phone_type:
  phone2:
  phone2_type:
  email: prudentmoney@aol.com
  url:

# CTAs:
#   first_CTA_text: Home Valuation
#   first_CTA_URL: /homevalue/
#   second_CTA_text: Home Search
#   second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Maximize Your Success"
    CTA_text: "Are you interested in learning about Elite Wealth and Tax Planning? We can help you."
    CTA_link_text: "Contact Me"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Looking for a Southern California Home?"
#     CTA_text2: "Search the entire MLS for your Southern California home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Southern California Wealth Management Podcast with Rene Castro'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in Wealth Management'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND.'
  keywords: 'Wealth Management, Wealth Management agents, top Wealth Management agents, local Wealth Management agents, find a Wealth Management agent, houses for sale in Southern California, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, Wealth Management market, estate agent, realestate, Wealth Management, buying a house, homes for sale, mls, home buyer'
  author: 'Rene Castro'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  # hero_text: Southern California Wealth Management Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#2ce881'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(250,250,250,.75)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
